# Generated by Django 3.0.1 on 2020-01-25 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200126_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
    ]
